import { createTheme } from "@uiw/codemirror-themes";
import { tags as t } from "@lezer/highlight";

export const cursorDarkTheme = createTheme({
  theme: "dark",
  settings: {
    background: "#191919",
    backgroundImage: "",
    foreground: "#d4d4d4",
    caret: "#d4d4d4",
    selection: "rgba(78,158,255,0.28)",
    selectionMatch: "rgba(78,158,255,0.14)",
    lineHighlight: "rgba(255,255,255,0.04)",
    gutterBackground: "#191919",
    gutterForeground: "#4e4e4e",
    gutterActiveForeground: "#858585",
    gutterBorder: "transparent",
    fontFamily: "inherit",
  },
  styles: [
    { tag: t.comment,                  color: "#6a9955" },
    { tag: t.lineComment,              color: "#6a9955" },
    { tag: t.blockComment,             color: "#6a9955" },
    { tag: t.docComment,               color: "#6a9955" },
    { tag: t.keyword,                  color: "#569cd6" },
    { tag: t.controlKeyword,           color: "#c586c0" },
    { tag: t.operatorKeyword,          color: "#569cd6" },
    { tag: t.definitionKeyword,        color: "#569cd6" },
    { tag: t.moduleKeyword,            color: "#c586c0" },
    { tag: t.string,                   color: "#ce9178" },
    { tag: t.special(t.string),        color: "#ce9178" },
    { tag: t.regexp,                   color: "#d16969" },
    { tag: t.number,                   color: "#b5cea8" },
    { tag: t.bool,                     color: "#569cd6" },
    { tag: t.null,                     color: "#569cd6" },
    { tag: t.variableName,             color: "#9cdcfe" },
    { tag: t.local(t.variableName),    color: "#9cdcfe" },
    { tag: t.definition(t.variableName), color: "#9cdcfe" },
    { tag: t.function(t.variableName), color: "#dcdcaa" },
    { tag: t.definition(t.function(t.variableName)), color: "#dcdcaa" },
    { tag: t.propertyName,             color: "#9cdcfe" },
    { tag: t.function(t.propertyName), color: "#dcdcaa" },
    { tag: t.typeName,                 color: "#4ec9b0" },
    { tag: t.className,                color: "#4ec9b0" },
    { tag: t.definition(t.typeName),   color: "#4ec9b0" },
    { tag: t.tagName,                  color: "#569cd6" },
    { tag: t.attributeName,            color: "#9cdcfe" },
    { tag: t.attributeValue,           color: "#ce9178" },
    { tag: t.namespace,                color: "#4ec9b0" },
    { tag: t.operator,                 color: "#d4d4d4" },
    { tag: t.compareOperator,          color: "#d4d4d4" },
    { tag: t.punctuation,              color: "#d4d4d4" },
    { tag: t.separator,                color: "#d4d4d4" },
    { tag: t.bracket,                  color: "#d4d4d4" },
    { tag: t.angleBracket,             color: "#808080" },
    { tag: t.self,                     color: "#569cd6" },
    { tag: t.meta,                     color: "#569cd6" },
    { tag: t.emphasis,                 fontStyle: "italic" },
    { tag: t.strong,                   fontWeight: "bold" },
    { tag: t.heading,                  color: "#569cd6", fontWeight: "bold" },
    { tag: t.heading1,                 color: "#569cd6", fontWeight: "bold" },
    { tag: t.heading2,                 color: "#569cd6", fontWeight: "bold" },
    { tag: t.link,                     color: "#ce9178", textDecoration: "underline" },
    { tag: t.url,                      color: "#ce9178" },
    { tag: t.invalid,                  color: "#f44747" },
  ],
});
